config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      member do
        post 'likes' => 'posts#likes', as: :likes
      end
      resources :comments, only: [:create, :new, :destroy, :index]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end


  root "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  validates :text, presence: true
  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter

  def recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.includes(:author).order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::API
  before_action :set_default_format

  private

  def set_default_format
    request.format = :json
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    post = Post.find(params[:post_id])
    comments = post.comments
    render json: comments
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = User.find(params[:user_id])
    @comment.post = Post.find(params[:post_id])
    if @comment.save
      render json: { status: 'Success', data: @comment }
    else
      render json: { status: 'Failure', error: @comment.errors.full_messages }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    user = User.find(params[:user_id])
    posts = user.posts
    render json: posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    if @user.id != current_user.id
      flash[:alert] = 'You cannot create comments for another user.'
      redirect_to root_path and return
    end
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user
    if @comment.save
      redirect_to user_posts_path, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to user_post_path(@post), notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post = Post.find(params[:post_id])
    if @like.save
      flash[:notice] = 'Like added successfully!'
      redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
    else
      flash[:alert] = "Couln't add a like!"
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.author
    redirect_to user_post_path(@user, @post) if params[:post_number]
    @post_number = @user.posts.find_index(@post) + 1
    @like = @post.likes.find_by(author: current_user)
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end

  before_action :set_user

  def new
    @post = @user.posts.new
  end

  def likes
    @post = Post.find(params[:id])
    if @post.likes.create(author_id: current_user.id)
      flash[:success] = 'You liked the post.'
    else
      flash[:error] = 'Failed to like the post.'
    end
    redirect_to user_posts_path
  end

  def create
    @user = User.find(params[:user_id])

    if @user.id != current_user.id
      flash[:alert] = 'You cannot create posts for another user.'
      redirect_to root_path and return
    end

    @post = current_user.posts.build(post_params)
    @post.author_id = current_user.id

    if @post.save
      puts 'post was saved successfully'
      redirect_to root_path, notice: 'Post was successfully created.'
    else
      puts 'post was not saved successfully'
      p @post.errors
      render :new
    end
  end

  def comments
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def destroy
    @post.likes.destroy_all
    @post.comments.destroy_all
    @post.destroy
    @user.update(posts_counter: @user.posts_counter - 1)
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/posts_controllers.rb
class PostsController < ApplicationController
  def index; end

  def show; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(posts_counter: :asc)
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.recent_posts
  end
end

app/helpers/api/v1/application_helper.rb
module Api::V1::ApplicationHelper
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<div class="form-container border-black">
  <h1>New Comment</h1>

  <%= form_with model: @comment, url: user_post_comments_path, class: "form", local: true do |form| %>
    <div class="form-items">
      <%= form.text_area :text, class: "form-fields border-black form-text", placeholder: "Write a comment..." %>
    </div>
    <div>
      <%= form.submit "Create comment", class: "comment-btn" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "user", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "post", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "comment", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<section>
  <%= render partial: "shared/user", locals: { user: @user } %>
  
    <% @user.posts.includes(:author).each_with_index do |post, index| %>

    <%= link_to user_post_path(user_id: post.author.id, id: post.id), class: "post" do %>
      <%= render "shared/post", post: post %>
      <div class="comments">
        <%= render "shared/comment", post: post %>
      </div>
    <% end %>
  <% end %>
  <button type="button" class="btn">Pagination</button>
</section>

app/views/posts/new.html.erb
<div class="form-container border-black">
  <h1>New Post</h1>

  <%= render "shared/form", post: @post %>

  <p class="back"><%=link_to 'Back to posts', user_posts_path %></p>
<div>

app/views/posts/show.html.erb
<section class= 'full-post-section'>
<div class='full-post border-black'>
  <h2>Post #<%= @post.id %> by <%= @post.author.name %></h2>
  <p class="post-likes-comments">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
    <p><%= @post.text %></p>
  
</div>

<div class="like-comment-btn">
<%= form_with model: @like, url:  user_posts_path(user_id: @post.author.id, post_id: @post.id), local: true do |form| %>
  <%= form.submit "Like", class: "btn" %>
<% end %>
<button type="button" class="btn"><%= link_to "Add a comment", new_user_post_comment_path(user_id: @post.author.id, post_id: @post.id)  %></button>
</div>

<div class='comments'>
  <% @post.comments.each do |comment| %>
    <p><%= comment.author.name %>: <%= comment.text %></p>
    <% if comment.author == current_user || @post.author == current_user %>
      <%= form_for([@user, @post, comment], method: :delete) do |f| %>
        <%= f.submit 'Delete comment', class: "comment-btn" %>
      <% end %>
    <% end %>
  <% end %>
</div>

<% if @post.author == current_user %>
  <%= form_with url: user_post_path(@user, @post), method: :delete do |form| %>
    <%= form.submit "Delete Post" , class: "btn"%>
  <% end %>
<% end %>
</section>

app/views/shared/_comment.html.erb
<% if (post.comments.empty?) %>
  <p>No comment yet.</p>
<% else %>
  <% post.comments.includes(:author).each do |comment| %>
    <ul>
      <li><%= comment.author.name %>: <%= comment.text %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: post, url: user_posts_path, local: true, class: "form" do |form| %>
    <div class="form-items">
      <%= form.label :title %></br>
      <%= form.text_field :title, class: "form-fields border-black form-title" %>
    </div>
    <div class="form-items">
      <%= form.label :text %></br>
      <%= form.text_area :text, class: "form-fields border-black form-text" %>
    </div>
    <div>
      <%= form.submit "Create post", class: "btn" %>
    </div>
  <% end %>

app/views/shared/_post.html.erb
<div class="user-post border-black">
  <h2>Post <%= post.id %></h2>
  <p><%= truncate(post.text, length: 150, omission: "...") %></p>
  <div class="like-comment">
    <p>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p> 
  </div>
</div>

app/views/shared/_user.html.erb
<%= link_to user_path(user), class: "user-list-item" do %>
    <img src="<%= user.photo %>" alt="avatar" class="border-black">
    <div class="user-info border-black">
      <h2><%= user.name %></h2>
      <p>Number of posts: <%= user.posts_counter %></p>
    </div>
  <% end %>

app/views/users/index.html.erb
<section>
<h1>List of users:</h1>
  <%= render partial: "shared/user", collection: @users, as: :user %>
</section>

app/views/users/show.html.erb
<section>
  <%= render "shared/user", user: @user %>
  <div class="bio border-black">
    <p>Bio</p>
    <p><%= @user.bio %></p>
  </div>
  <div class="posts">
    <% @recent_posts.each do |post| %>
      <%= render "shared/post", post: post %>
    <% end %>
  </div>
  <button type="button" class="btn"><%= link_to "See all posts", user_posts_path(@user)  %></button>
  <button type="button" class="btn"><%= link_to "Create a post", new_user_post_path(@user) %></button>
</section>